Library/Controllers/BooksController.cs
using Library.Extensions;
using Library.Models;
using Library.Services.Abstracts;
using Library.Services.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers;

public class BooksController : Controller
{
    private readonly IBookService _bookService;
    private readonly ICategoryService _categoryService;
    private readonly IFileService _fileService;
    private readonly IUserService _userService;

    public BooksController(
        IBookService bookService, 
        ICategoryService categoryService, 
        IFileService fileService, IUserService userService)
    {
        _bookService = bookService;
        _categoryService = categoryService;
        _fileService = fileService;
        _userService = userService;
    }

    [HttpGet]
    public IActionResult Home(int currentPage = 1)
    {
        var books = _bookService.GetAllQueryable();
        int pageSize = 8;
        int count = books.Count();
        var paginationBooks = books.Skip((currentPage - 1) * pageSize).Take(pageSize).MapToShortBooksViewModel();

        BooksPageViewModel booksPageViewModel = new BooksPageViewModel()
        {
            Books = paginationBooks,
            Pagination = new PaginationViewModel(count, currentPage, pageSize)
        };

        return View(booksPageViewModel);
    }

    [HttpGet]
    public IActionResult CreateBook()
    {
        CreateBookViewModel createBookViewModel = new CreateBookViewModel
        {
            Categories = _categoryService.GetAll()
        };
        return View(createBookViewModel);
    }
    
    [HttpPost]
    public IActionResult CreateBook(CreateBookViewModel createBookViewModel, IFormFile uploadedFile)
    {
        bool fileValid = _fileService.ValidFile(uploadedFile);
        if (ModelState.IsValid && fileValid)
        {
            Book book = createBookViewModel.Book.MapToBookModel();
            book.ImgPath = _fileService.SaveFileAndGetPath(book, uploadedFile);
            _bookService.Add(book);
            return RedirectToAction("Home");
        }
        return RedirectToAction("CreateBook");
    }
    
    [HttpGet]
    public IActionResult About(int id)
    {
        BookViewModel? bookViewModel = _bookService.GetById(id);
        if (bookViewModel is null) return NotFound();
        
        AboutPageViewModel aboutPageViewModel = new AboutPageViewModel()
        {
            Book = bookViewModel
        };
        return View(aboutPageViewModel);
    }

    [HttpPost]
    public IActionResult TakeBook(AboutPageViewModel aboutPageViewModel)
    {
        if (ModelState.IsValid)
        {
            var userMail = aboutPageViewModel.AuthorUser.Mail;
            var userBooks = _userService.GetUserBooks(userMail);
            if (userBooks.Count > 2)
                return View();
            

            BookViewModel book = _bookService.GetById(aboutPageViewModel.Book.Id);
            if (book.UserId != null)
                return NotFound();
            var user = _userService.GetByMail(userMail);
            book.UserId = user.Id;
            _bookService.TakeBook(book.MapToBookModel());
            return RedirectToAction("Cabinet", "Users", new {mail = userMail});
        }
        return NotFound();
    }

    [HttpPost]
    public IActionResult TakeBookFromHome(BooksPageViewModel booksPageViewModel)
    {
        if (ModelState.IsValid)
        {
            var userMail = booksPageViewModel.AuthorUser.Mail;
            var userBooks = _userService.GetUserBooks(userMail);
            if (userBooks.Count > 2)
                return View("TakeBook");
            
            BookViewModel book = _bookService.GetById(booksPageViewModel.BookId);
            if (book.UserId != null)
                return NotFound();
            var user = _userService.GetByMail(userMail);
            book.UserId = user.Id;
            _bookService.TakeBook(book.MapToBookModel());
            return RedirectToAction("Cabinet", "Users", new {mail = userMail});
        }

        return NotFound();
    }
    
    [HttpGet]
    public IActionResult GiveBook(int id)
    {
        Book book = _bookService.GetById(id).MapToBookModel();
        if (book is null) return NotFound();
        _bookService.GiveBook(book);
        return View();
    }
    
    [HttpGet]
    public IActionResult Delete(int id)
    {
        BookViewModel? bookViewModel = _bookService.GetById(id);
        if (bookViewModel is null) return NotFound();
        Book? book = bookViewModel.MapToBookModel();
        _bookService.DeleteBook(book);
        
        return RedirectToAction("Home");
    }
    [HttpGet]
    public IActionResult Edit(int id)
    {
        BookViewModel? bookViewModel = _bookService.GetById(id);
        if (bookViewModel is null) return NotFound();
        CreateBookViewModel createBookViewModel = new CreateBookViewModel()
        {
            Book = bookViewModel,
            Categories = _categoryService.GetAll()
        };
        
        return View(createBookViewModel);
    }
    
    [HttpPost]
    public IActionResult Edit(CreateBookViewModel createBookViewModel, IFormFile uploadedFile)
    {
        bool fileValid = _fileService.ValidFile(uploadedFile);
        if (ModelState.IsValid && fileValid)
        {
            Book book = createBookViewModel.Book.MapToBookModel();
            book.ImgPath = _fileService.SaveFileAndGetPath(book, uploadedFile);
            _bookService.Update(book);
            return RedirectToAction("Home");
        }
        return RedirectToAction("CreateBook");
    }

    [HttpGet]
    public IActionResult AllTakenBook()
    {
        List<BookViewModel> books = _bookService.GetAllTakenBook();
        return View(books);
    }
}

Library/Controllers/CategoriesController.cs
using Library.Extensions;
using Library.Models;
using Library.Services.Abstracts;
using Library.Services.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers;

public class CategoriesController : Controller
{
    private readonly ICategoryService _categoryService;

    public CategoriesController(ICategoryService categoryService)
    {
        _categoryService = categoryService;
    }

    [HttpGet]
    public IActionResult CreateCategory()
    {
        CreateCategoryViewModel createCategoryViewModel = new CreateCategoryViewModel()
        {
            Categories = _categoryService.GetAll()
        };
        return View(createCategoryViewModel);
    }
    
    [HttpPost]
    public IActionResult CreateCategory(CreateCategoryViewModel createCategoryViewModel)
    {
        if (ModelState.IsValid)
        {
            Category category = createCategoryViewModel.Category.MapToCategoryModel();
            _categoryService.Add(category);
        }
        return RedirectToAction("CreateCategory");
    }

    [HttpGet]
    public IActionResult Delete(int id)
    {
        Category? category = _categoryService.GetById(id);
        if (category is null) return NotFound();
        _categoryService.Delete(category);

        return RedirectToAction("CreateCategory");
    }
}

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Library.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Books" asp-action="Home">Главная</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="CreateCategory">Добавить категории</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="CreateBook">Добавить книгу</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Authorization">Личный кабинет</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="AllTakenBook">Список всех выданных книг</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3 min-vh-100">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - Library - <a asp-area="" asp-controller="" asp-action="">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>